function systemConfig = createM3ContractConfig()
%createM3ContractConfig Create the non-runnable M3 contract baseline.

placeholderComponent = struct( ...
    'id', "PLACEHOLDER", ...
    'status', "PLACEHOLDER", ...
    'sourceTag', "PLACEHOLDER", ...
    'identityScope', "PLACEHOLDER", ...
    'requiredParametersComplete', false);
controlComponent = placeholderComponent;
controlComponent.candidatePathId = "PLACEHOLDER";

systemConfig = struct( ...
    'systemConfigId', "M3-PD-CONTRACT-v01", ...
    'isContractBaseline', true, ...
    'candidatePathId', "PLACEHOLDER", ...
    'components', struct( ...
        'battery', placeholderComponent, ...
        'hvPath', placeholderComponent, ...
        'inverter', placeholderComponent, ...
        'motor', placeholderComponent, ...
        'control', controlComponent, ...
        'thermal', placeholderComponent, ...
        'protection', placeholderComponent, ...
        'scenario', placeholderComponent), ...
    'compatibility', struct( ...
        'voltage', "unknown", ...
        'current', "unknown", ...
        'powerEnergy', "unknown", ...
        'thermal', "unknown", ...
        'controlTiming', "unknown", ...
        'mechanical', "unknown", ...
        'protection', "unknown", ...
        'dataSource', "unknown"), ...
    'optionalDataGaps', [ ...
        "candidate path is not selected"; ...
        "device configurations are not registered"], ...
    'researchScope', "");
end
