function build_pulse_heating_single_pack_v03a(enableDirectModulation)
%BUILD_PULSE_HEATING_SINGLE_PACK_V03A Build the v03-A Simscape topology.
%
% This script uses Simulink/Simscape public APIs to create a clean
% single-pack, controller-test-source, single-PMSM pulse-heating model.
% It intentionally does not modify v01/v02; it overwrites only the v03
% working model. Set enableDirectModulation=false when v03-B will provide
% the modulation signal through a current-loop controller.

    if nargin < 1
        enableDirectModulation = true;
    end

    modelName = "pulse_heating_single_pack_v03";
    modelFile = modelName + ".slx";
    scriptDir = string(fileparts(mfilename("fullpath")));
    projectDir = fileparts(scriptDir);
    modelDir = fullfile(projectDir, "02_模型");
    oldDir = string(pwd);
    cleanupObj = onCleanup(@() cd(oldDir));
    cd(modelDir);

    if bdIsLoaded(modelName)
        close_system(modelName, 0);
    end

    if isfile(modelFile)
        delete(modelFile);
    end

    new_system(modelName);
    open_system(modelName);

    pack = buildOfficialBecPackParams();

    set_param(modelName, ...
        "Solver", "ode23t", ...
        "StopTime", "1", ...
        "MaxStep", "1e-4");

    add_block("batt_lib/Cells/Battery Equivalent Circuit", modelName + "/Battery_Pack", ...
        "Position", [100 120 260 320]);
    configureOfficialBecPack(modelName + "/Battery_Pack", pack);

    add_block("ee_lib/Passive/Capacitor", modelName + "/DC_link_Cap", ...
        "Position", [390 90 460 160]);
    set_param(modelName + "/DC_link_Cap", ...
        "c", "1e-3", ...
        "vc_specify", "on", ...
        "vc", mat2str(pack.initial_ocv_V));
    add_block("fl_lib/Electrical/Electrical Elements/Electrical Reference", modelName + "/Elec_Ref", ...
        "Position", [400 250 450 300]);
    add_block("nesl_utility/Solver Configuration", modelName + "/Solver_Config", ...
        "Position", [400 330 470 390]);
    add_block("fl_lib/Thermal/Thermal Elements/Convective Heat Transfer", modelName + "/Conv_HT", ...
        "Position", [160 380 240 430]);
    add_block("fl_lib/Thermal/Thermal Elements/Thermal Reference", modelName + "/Thermal_Ref", ...
        "Position", [290 380 350 430]);

    add_block("fl_lib/Electrical/Electrical Sensors/Current Sensor", modelName + "/I_bat_Sensor", ...
        "Position", [300 100 350 150]);
    add_block("fl_lib/Electrical/Electrical Sensors/Voltage Sensor", modelName + "/V_bat_Sensor", ...
        "Position", [300 185 350 235]);

    add_block("ee_lib/Semiconductors & Converters/Converters/Average-Value Voltage Source Converter (Three-Phase)", ...
        modelName + "/VSC_Avg_Test", "Position", [560 105 690 235]);
    set_param(modelName + "/VSC_Avg_Test", "input_option", "Modulation waveforms");

    add_block("ee_lib/Sensors & Transducers/Current Sensor (Three-Phase)", modelName + "/Iabc_Sensor", ...
        "Position", [760 120 850 210]);
    add_block("ee_lib/Electromechanical/Permanent Magnet/PMSM", modelName + "/PMSM", ...
        "Position", [930 100 1060 250]);
    add_block("fl_lib/Mechanical/Rotational Elements/Mechanical Rotational Reference", modelName + "/Mech_Ref", ...
        "Position", [1130 235 1190 290]);

    add_block("nesl_utility/Simulink-PS Converter", modelName + "/SPS_ModWave", ...
        "Position", [280 545 350 585]);

    if enableDirectModulation
        add_block("simulink/Sources/Sine Wave", modelName + "/ma_cmd", ...
            "Position", [90 500 140 530], "Amplitude", "0.05", "Frequency", "2*pi*1250", "Phase", "0");
        add_block("simulink/Sources/Sine Wave", modelName + "/mb_cmd", ...
            "Position", [90 545 140 575], "Amplitude", "0.05", "Frequency", "2*pi*1250", "Phase", "-2*pi/3");
        add_block("simulink/Sources/Sine Wave", modelName + "/mc_cmd", ...
            "Position", [90 590 140 620], "Amplitude", "0.05", "Frequency", "2*pi*1250", "Phase", "2*pi/3");
        add_block("simulink/Signal Routing/Mux", modelName + "/ModWave_mux", ...
            "Position", [190 520 220 610], "Inputs", "3");
    end

    add_block("nesl_utility/PS-Simulink Converter", modelName + "/PSS_Ibat", ...
        "Position", [430 505 500 535]);
    add_block("nesl_utility/PS-Simulink Converter", modelName + "/PSS_Vbat", ...
        "Position", [430 550 500 580]);
    add_block("nesl_utility/PS-Simulink Converter", modelName + "/PSS_Iabc", ...
        "Position", [880 515 950 545]);

    addToWorkspace(modelName, "I_battery_terminal_log", [540 505 650 535]);
    addToWorkspace(modelName, "V_battery_terminal_log", [540 550 650 580]);
    addToWorkspace(modelName, "Iabc_motor_log", [990 515 1100 545]);
    addToWorkspace(modelName, "batteryCurrent_log", [330 650 460 680]);
    addToWorkspace(modelName, "batteryTemperature_log", [330 695 460 725]);
    addToWorkspace(modelName, "batteryVoltage_log", [330 740 460 770]);
    addToWorkspace(modelName, "socCell_log", [330 785 460 815]);
    add_block("simulink/Sources/Constant", modelName + "/batteryTemperature_const", ...
        "Position", [180 695 285 725], "Value", string(pack.temperature_K));
    add_block("simulink/Sources/Constant", modelName + "/socCell_const", ...
        "Position", [180 785 285 815], "Value", string(pack.soc_init));

    % Signal lines.
    if enableDirectModulation
        add_line(modelName, "ma_cmd/1", "ModWave_mux/1", "autorouting", "on");
        add_line(modelName, "mb_cmd/1", "ModWave_mux/2", "autorouting", "on");
        add_line(modelName, "mc_cmd/1", "ModWave_mux/3", "autorouting", "on");
        add_line(modelName, "ModWave_mux/1", "SPS_ModWave/1", "autorouting", "on");
    end

    add_line(modelName, "PSS_Ibat/1", "I_battery_terminal_log/1", "autorouting", "on");
    add_line(modelName, "PSS_Vbat/1", "V_battery_terminal_log/1", "autorouting", "on");
    add_line(modelName, "PSS_Iabc/1", "Iabc_motor_log/1", "autorouting", "on");
    add_line(modelName, "PSS_Ibat/1", "batteryCurrent_log/1", "autorouting", "on");
    add_line(modelName, "PSS_Vbat/1", "batteryVoltage_log/1", "autorouting", "on");
    add_line(modelName, "batteryTemperature_const/1", "batteryTemperature_log/1", "autorouting", "on");
    add_line(modelName, "socCell_const/1", "socCell_log/1", "autorouting", "on");

    % Physical and physical-signal connections by port handles.
    packPorts = get_param(modelName + "/Battery_Pack", "PortHandles");
    cap = get_param(modelName + "/DC_link_Cap", "PortHandles");
    ref = get_param(modelName + "/Elec_Ref", "PortHandles");
    solver = get_param(modelName + "/Solver_Config", "PortHandles");
    conv = get_param(modelName + "/Conv_HT", "PortHandles");
    thref = get_param(modelName + "/Thermal_Ref", "PortHandles");
    ibat = get_param(modelName + "/I_bat_Sensor", "PortHandles");
    vbat = get_param(modelName + "/V_bat_Sensor", "PortHandles");
    vsc = get_param(modelName + "/VSC_Avg_Test", "PortHandles");
    iabc = get_param(modelName + "/Iabc_Sensor", "PortHandles");
    pmsm = get_param(modelName + "/PMSM", "PortHandles");
    mech = get_param(modelName + "/Mech_Ref", "PortHandles");
    sps = get_param(modelName + "/SPS_ModWave", "PortHandles");
    pssIbat = get_param(modelName + "/PSS_Ibat", "PortHandles");
    pssVbat = get_param(modelName + "/PSS_Vbat", "PortHandles");
    pssIabc = get_param(modelName + "/PSS_Iabc", "PortHandles");

    add_line(modelName, packPorts.LConn(1), ibat.LConn(1), "autorouting", "on");
    add_line(modelName, ibat.RConn(2), cap.LConn(1), "autorouting", "on");
    add_line(modelName, cap.LConn(1), vsc.RConn(1), "autorouting", "on");
    add_line(modelName, cap.LConn(1), vbat.LConn(1), "autorouting", "on");

    add_line(modelName, packPorts.RConn(1), cap.RConn(1), "autorouting", "on");
    add_line(modelName, cap.RConn(1), vsc.RConn(2), "autorouting", "on");
    add_line(modelName, cap.RConn(1), vbat.RConn(2), "autorouting", "on");
    add_line(modelName, cap.RConn(1), ref.LConn(1), "autorouting", "on");
    add_line(modelName, cap.RConn(1), solver.RConn(1), "autorouting", "on");

    add_line(modelName, packPorts.RConn(2), conv.LConn(1), "autorouting", "on");
    add_line(modelName, conv.RConn(1), thref.LConn(1), "autorouting", "on");

    add_line(modelName, sps.RConn(1), vsc.LConn(1), "autorouting", "on");
    add_line(modelName, vsc.LConn(2), iabc.LConn(1), "autorouting", "on");
    add_line(modelName, iabc.RConn(2), pmsm.LConn(1), "autorouting", "on");
    add_line(modelName, pmsm.LConn(2), cap.RConn(1), "autorouting", "on");
    add_line(modelName, pmsm.RConn(1), mech.LConn(1), "autorouting", "on");
    add_line(modelName, pmsm.RConn(2), mech.LConn(1), "autorouting", "on");

    add_line(modelName, ibat.RConn(1), pssIbat.LConn(1), "autorouting", "on");
    add_line(modelName, vbat.RConn(1), pssVbat.LConn(1), "autorouting", "on");
    add_line(modelName, iabc.RConn(1), pssIabc.LConn(1), "autorouting", "on");

    save_system(modelName, modelFile);
    fprintf("Built %s\n", modelFile);
end

function pack = buildOfficialBecPackParams()
    % MATLAB/Simscape Battery R2025b official default cell data, scaled to a
    % generic pack. 216 cells in series gives about 802 V at 50% SOC.
    pack.N_series = 216;
    pack.N_parallel = 1;
    pack.soc_init = 0.50;
    pack.temperature_K = 278.15;

    pack.BatteryCapacity_Ah = 27 * pack.N_parallel;
    pack.SOCBreakpoints = [0, .1, .25, .5, .75, .9, 1];
    pack.TemperatureBreakpoints_K = [278, 293, 313];
    pack.ResistanceCurrentBreakpoints_A = [-1, 0, 1] * pack.N_parallel;

    pack.OpenCircuitVoltage_V = pack.N_series * [3.5057, 3.566, 3.6337, 3.7127, 3.9259, 4.0777, 4.1928];
    pack.initial_ocv_V = interp1(pack.SOCBreakpoints, pack.OpenCircuitVoltage_V, pack.soc_init, "linear");
    pack.OpenCircuitVoltageThermal_V = pack.N_series * [ ...
        3.49, 3.5, 3.51; ...
        3.55, 3.57, 3.56; ...
        3.62, 3.63, 3.64; ...
        3.71, 3.71, 3.72; ...
        3.91, 3.93, 3.94; ...
        4.07, 4.08, 4.08; ...
        4.19, 4.19, 4.19];

    resistanceScale = pack.N_series / pack.N_parallel;
    pack.R0_Ohm = resistanceScale * [.0085, .0085, .0087, .0082, .0083, .0085, .0085];
    pack.R0Thermal_Ohm = resistanceScale * [ ...
        .0117, .0085, .009; ...
        .011, .0085, .009; ...
        .0114, .0087, .0092; ...
        .0107, .0082, .0088; ...
        .0107, .0083, .0091; ...
        .0113, .0085, .0089; ...
        .0116, .0085, .0089];

    rcResistance = resistanceScale * [.0029, .0024, .0026, .0016, .0023, .0018, .0017];
    rcResistanceThermal = resistanceScale * [ ...
        .0109, .0029, .0013; ...
        .0069, .0024, .0012; ...
        .0047, .0026, .0013; ...
        .0034, .0016, .001; ...
        .0033, .0023, .0014; ...
        .0033, .0018, .0011; ...
        .0028, .0017, .0011];
    rcTau = [36, 45, 105, 29, 77, 33, 39];
    rcTauThermal = [ ...
        20, 36, 39; ...
        31, 45, 39; ...
        109, 105, 61; ...
        36, 29, 26; ...
        59, 77, 67; ...
        40, 33, 29; ...
        25, 39, 33];

    pack.R1_Ohm = rcResistance;
    pack.R2_Ohm = rcResistance;
    pack.R3_Ohm = rcResistance;
    pack.Tau1_s = rcTau;
    pack.Tau2_s = rcTau;
    pack.Tau3_s = rcTau;
    pack.R1Thermal_Ohm = rcResistanceThermal;
    pack.R2Thermal_Ohm = rcResistanceThermal;
    pack.R3Thermal_Ohm = rcResistanceThermal;
    pack.Tau1Thermal_s = rcTauThermal;
    pack.Tau2Thermal_s = rcTauThermal;
    pack.Tau3Thermal_s = rcTauThermal;
    pack.ThermalMass_J_per_K = 100 * pack.N_series * pack.N_parallel;
end

function configureOfficialBecPack(blockPath, pack)
    set_param(blockPath, ...
        "BatteryCapacity", mat2str(pack.BatteryCapacity_Ah), ...
        "ThermalModel", "simscape.battery.enum.cells.BatteryThermalModel.LumpedThermalMass", ...
        "SOCBreakpoints", mat2str(pack.SOCBreakpoints), ...
        "TemperatureBreakpoints", mat2str(pack.TemperatureBreakpoints_K), ...
        "ResistanceCurrentBreakpoints", mat2str(pack.ResistanceCurrentBreakpoints_A), ...
        "OpenCircuitVoltage", mat2str(pack.OpenCircuitVoltage_V), ...
        "OpenCircuitVoltageThermal", mat2str(pack.OpenCircuitVoltageThermal_V), ...
        "R0", mat2str(pack.R0_Ohm), ...
        "R0I", mat2str(pack.R0Thermal_Ohm), ...
        "R0Thermal", mat2str(pack.R0Thermal_Ohm), ...
        "R0ThermalI", "repmat(" + mat2str(pack.R0Thermal_Ohm) + ", 1, 1, 3)", ...
        "DischargeR1", mat2str(pack.R1_Ohm), ...
        "ChargeR1", mat2str(pack.R1_Ohm), ...
        "DischargeR2", mat2str(pack.R2_Ohm), ...
        "ChargeR2", mat2str(pack.R2_Ohm), ...
        "DischargeR3", mat2str(pack.R3_Ohm), ...
        "ChargeR3", mat2str(pack.R3_Ohm), ...
        "DischargeTau1", mat2str(pack.Tau1_s), ...
        "ChargeTau1", mat2str(pack.Tau1_s), ...
        "DischargeTau2", mat2str(pack.Tau2_s), ...
        "ChargeTau2", mat2str(pack.Tau2_s), ...
        "DischargeTau3", mat2str(pack.Tau3_s), ...
        "ChargeTau3", mat2str(pack.Tau3_s), ...
        "DischargeR1Thermal", mat2str(pack.R1Thermal_Ohm), ...
        "ChargeR1Thermal", mat2str(pack.R1Thermal_Ohm), ...
        "DischargeR2Thermal", mat2str(pack.R2Thermal_Ohm), ...
        "ChargeR2Thermal", mat2str(pack.R2Thermal_Ohm), ...
        "DischargeR3Thermal", mat2str(pack.R3Thermal_Ohm), ...
        "ChargeR3Thermal", mat2str(pack.R3Thermal_Ohm), ...
        "DischargeTau1Thermal", mat2str(pack.Tau1Thermal_s), ...
        "ChargeTau1Thermal", mat2str(pack.Tau1Thermal_s), ...
        "DischargeTau2Thermal", mat2str(pack.Tau2Thermal_s), ...
        "ChargeTau2Thermal", mat2str(pack.Tau2Thermal_s), ...
        "DischargeTau3Thermal", mat2str(pack.Tau3Thermal_s), ...
        "ChargeTau3Thermal", mat2str(pack.Tau3Thermal_s), ...
        "BatteryThermalMass", mat2str(pack.ThermalMass_J_per_K), ...
        "SimulationTemperature", mat2str(pack.temperature_K), ...
        "stateOfCharge_specify", "on", ...
        "stateOfCharge", mat2str(pack.soc_init), ...
        "batteryTemperature_specify", "on", ...
        "batteryTemperature", mat2str(pack.temperature_K), ...
        "batteryVoltage_specify", "off");
end

function addToWorkspace(modelName, variableName, position)
    add_block("simulink/Sinks/To Workspace", modelName + "/" + variableName, ...
        "Position", position, ...
        "VariableName", variableName, ...
        "SaveFormat", "Timeseries");
end
