function results = runM402BCompleteLedgerSensitivity(runMode)
% Run the M4-02B Reference / Platform complete-ledger sensitivity matrix.

if nargin < 1
    runMode = "all";
end

runMode = string(runMode);
modelName = 'pulse_heating_official_spine_v04';
assert(bdIsLoaded(modelName), ...
    'Load the active V4 model before running the M4-02B sensitivity matrix.');

scriptDir = fileparts(mfilename('fullpath'));
resultsDir = fullfile(fileparts(scriptDir), '04_仿真结果');
if ~isfolder(resultsDir)
    mkdir(resultsDir);
end

csvPath = fullfile(resultsDir, 'M4-02B_complete_ledger_sensitivity_v01.csv');
paths = resolveBlockPaths(modelName);
scenarios = createScenarios();

[scenarioIndices, enforceLedgerAssertions] = selectScenarios(scenarios, runMode);

records = repmat(emptyRecord(), numel(scenarioIndices), 1);
for k = 1:numel(scenarioIndices)
    scenario = scenarios(scenarioIndices(k), :);
    in = Simulink.SimulationInput(modelName);
    in = applyScenario(in, modelName, paths, scenario);
    out = sim(in);
    records(k) = collectRecord(out, scenario, enforceLedgerAssertions);
end

results = struct2table(records);
if enforceLedgerAssertions
    verifyResults(results);
end
if runMode == "preflight"
    verifyPreflight(results);
elseif runMode == "all"
    writetable(results, csvPath);
end
end

function [scenarioIndices, enforceLedgerAssertions] = selectScenarios(scenarios, runMode)
enforceLedgerAssertions = true;

switch runMode
    case "preflight"
        scenarioIndices = find(scenarios.Preflight);
    case "all"
        scenarioIndices = 1:height(scenarios);
    case "diagnose_b01"
        scenarioIndices = find(scenarios.Scenario_ID == "B01_HVPathR_Low");
        enforceLedgerAssertions = false;
    otherwise
        prefix = "diagnose:";
        if startsWith(runMode, prefix)
            scenarioId = extractAfter(runMode, prefix);
            scenarioIndices = find(scenarios.Scenario_ID == scenarioId);
            assert(isscalar(scenarioIndices), ...
                'Unknown or non-unique diagnostic scenario: %s', scenarioId);
            enforceLedgerAssertions = false;
        else
            error('Unsupported run mode: %s', runMode);
        end
end
end

function paths = resolveBlockPaths(modelName)
paths.HVPosR = Simulink.ID.getFullName([modelName ':740']);
paths.HVNegR = Simulink.ID.getFullName([modelName ':741']);
paths.DCLinkC = Simulink.ID.getFullName([modelName ':742']);
paths.PMSM = Simulink.ID.getFullName([modelName ':85']);
paths.RMSWindow = Simulink.ID.getFullName([modelName ':787']);
paths.HVLossGain = Simulink.ID.getFullName([modelName ':865']);
paths.DCLinkEnergyGain = Simulink.ID.getFullName([modelName ':867']);
paths.DCLinkEnergyInitial = Simulink.ID.getFullName([modelName ':868']);
paths.RsAudit = Simulink.ID.getFullName([modelName ':633']);
paths.RPackAudit = Simulink.ID.getFullName([modelName ':661']);
paths.IGBTRon = Simulink.ID.getFullName([modelName ':649']);
paths.IGBTVf = Simulink.ID.getFullName([modelName ':650']);
paths.Ambient = Simulink.ID.getFullName([modelName ':514']);
paths.Coolant = Simulink.ID.getFullName([modelName ':515']);
paths.IdPulse = Simulink.ID.getFullName([modelName ':532']);
paths.IdScale = Simulink.ID.getFullName([modelName ':533']);
paths.IdOffset = Simulink.ID.getFullName([modelName ':534']);
paths.IqRef = Simulink.ID.getFullName([modelName ':535']);
paths.LimitId = Simulink.ID.getFullName([modelName ':537']);
paths.LimitFrequency = Simulink.ID.getFullName([modelName ':538']);
paths.LimitDuty = Simulink.ID.getFullName([modelName ':539']);
paths.LimitPhase = Simulink.ID.getFullName([modelName ':540']);
paths.LimitMode = Simulink.ID.getFullName([modelName ':541']);
paths.LimitStatus = Simulink.ID.getFullName([modelName ':542']);
paths.ClosedLoopEnable = Simulink.ID.getFullName([modelName ':310']);
end

function scenarios = createScenarios()
nominal = nominalValues();

scenarioId = ["B00_Base"; "B01_HVPathR_Low"; "B02_HVPathR_High"; ...
    "B03_DCLinkC_Low"; "B04_DCLinkC_High"; "B05_Rs_Low"; ...
    "B06_Rs_High"; "B07_BattHeatR_Low"; "B08_BattHeatR_High"; ...
    "B09_BattThermalC_Low"; "B10_BattThermalC_High"; ...
    "B11_InvLoss_Low"; "B12_InvLoss_High"; "B13_InvThermalC_Low"; ...
    "B14_InvThermalC_High"; "B15_InvThermalR_Low"; ...
    "B16_InvThermalR_High"; "B17_CoolingBoundary_Low"; ...
    "B18_CoolingBoundary_High"; "T00_Base"; "T01_InvThermalC_Low"; ...
    "T02_InvThermalC_High"; "T03_InvThermalR_Low"; ...
    "T04_InvThermalR_High"; "T05_CoolingBoundary_Low"; ...
    "T06_CoolingBoundary_High"];
analysisTier = [repmat("ledger_40ms", 19, 1); repmat("thermal_200ms", 7, 1)];
family = ["baseline"; "physical_path"; "physical_path"; ...
    "physical_path"; "physical_path"; "physical_path"; "physical_path"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"; "thermal_ledger_proxy"; ...
    "thermal_ledger_proxy"; "thermal_ledger_proxy"];
variedParameter = ["none"; "HVPath_R"; "HVPath_R"; "DCLink_C"; ...
    "DCLink_C"; "Rs"; "Rs"; "M401C_R_batt_heat_ref_Ohm"; ...
    "M401C_R_batt_heat_ref_Ohm"; "M401C_C_batt_J_K"; ...
    "M401C_C_batt_J_K"; "M401C_IGBT_loss_package"; ...
    "M401C_IGBT_loss_package"; "M401C_C_inv_J_K"; ...
    "M401C_C_inv_J_K"; "M401C_Rth_inv_K_W"; ...
    "M401C_Rth_inv_K_W"; "ambient_coolant_boundary"; ...
    "ambient_coolant_boundary"; "none"; "M401C_C_inv_J_K"; ...
    "M401C_C_inv_J_K"; "M401C_Rth_inv_K_W"; ...
    "M401C_Rth_inv_K_W"; "ambient_coolant_boundary"; ...
    "ambient_coolant_boundary"];
sourceTag = ["M4-01C frozen baseline"; repmat("ENGINEERING_DEFAULT", 4, 1); ...
    repmat("OFFICIAL", 2, 1); repmat("OFFICIAL+ENGINEERING_DEFAULT", 2, 1); ...
    repmat("ENGINEERING_DEFAULT", 4, 1); ...
    repmat("OFFICIAL+ENGINEERING_DEFAULT", 2, 1); ...
    repmat("ENGINEERING_DEFAULT", 11, 1)];
semantics = ["Reference / Platform baseline"; ...
    "physical HV path"; "physical HV path"; ...
    "physical DC-link storage"; "physical DC-link storage"; ...
    "physical PMSM winding and copper-loss path"; ...
    "physical PMSM winding and copper-loss path"; ...
    "battery heat-source and ledger proxy only"; ...
    "battery heat-source and ledger proxy only"; ...
    "battery thermal-storage ledger proxy only"; ...
    "battery thermal-storage ledger proxy only"; ...
    "Reference inverter-loss ledger package only"; ...
    "Reference inverter-loss ledger package only"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "official-example thermal boundary with Reference override"; ...
    "official-example thermal boundary with Reference override"; ...
    "Reference / Platform baseline"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "Reference inverter thermal-pool only"; ...
    "official-example thermal boundary with Reference override"; ...
    "official-example thermal boundary with Reference override"];

N = numel(scenarioId);
family(20) = "baseline";
sourceTag(12:13) = "OFFICIAL+ENGINEERING_DEFAULT";
sourceTag(14:15) = "ENGINEERING_DEFAULT";
sourceTag(20) = "M4-01C frozen baseline";
hvPathR = repmat(nominal.HVPath_R_Ohm, N, 1);
dcLinkC = repmat(nominal.DCLink_C_F, N, 1);
rs = repmat(nominal.Rs_Ohm, N, 1);
rBattHeat = repmat(nominal.R_batt_heat_Ohm, N, 1);
cBatt = repmat(nominal.C_batt_J_K, N, 1);
ron = repmat(nominal.IGBT_Ron_Ohm, N, 1);
vf = repmat(nominal.IGBT_Vf_V, N, 1);
eon = repmat(nominal.IGBT_Eon_J, N, 1);
eoff = repmat(nominal.IGBT_Eoff_J, N, 1);
tdead = repmat(nominal.PWM_tdead_s, N, 1);
cInv = repmat(nominal.C_inv_J_K, N, 1);
rthInv = repmat(nominal.Rth_inv_K_W, N, 1);
ambient = repmat(nominal.Ambient_K, N, 1);
coolant = repmat(nominal.Coolant_K, N, 1);
windowStop = [repmat(0.08, 19, 1); repmat(0.20, 7, 1)];
% Run five audit ticks past the fixed analysis window to settle the ledger pipeline.
auditPublishGuard = repmat(5 * 2e-6, N, 1);
stopTime = windowStop + auditPublishGuard;

hvPathR([2, 3]) = [0.005; 0.02];
dcLinkC([4, 5]) = [235e-6; 940e-6];
rs([6, 7]) = [0.0065; 0.026];
rBattHeat([8, 9]) = nominal.R_batt_heat_Ohm * [0.5; 2.0];
cBatt([10, 11]) = nominal.C_batt_J_K * [0.5; 2.0];
ron([12, 13]) = nominal.IGBT_Ron_Ohm * [0.5; 2.0];
vf([12, 13]) = nominal.IGBT_Vf_V * [0.75; 1.5];
eon([12, 13]) = nominal.IGBT_Eon_J * [0.5; 2.0];
eoff([12, 13]) = nominal.IGBT_Eoff_J * [0.5; 2.0];
tdead([12, 13]) = nominal.PWM_tdead_s * [0.5; 2.0];
cInv([14, 15]) = nominal.C_inv_J_K * [0.5; 2.0];
rthInv([16, 17]) = nominal.Rth_inv_K_W * [0.5; 2.0];
ambient([18, 19]) = [258.15; 268.15];
coolant([18, 19]) = [258.15; 268.15];
cInv([21, 22]) = nominal.C_inv_J_K * [0.5; 2.0];
rthInv([23, 24]) = nominal.Rth_inv_K_W * [0.5; 2.0];
ambient([25, 26]) = [258.15; 268.15];
coolant([25, 26]) = [258.15; 268.15];

windowDuration = repmat(0.04, N, 1);
windowStart = windowStop - windowDuration;
preflight = false(N, 1);
preflight([1, 3, 5, 7, 9, 11, 13, 15, 17, 19]) = true;

scenarios = table(scenarioId, analysisTier, family, variedParameter, sourceTag, ...
    semantics, hvPathR, dcLinkC, rs, rBattHeat, cBatt, ron, vf, eon, eoff, ...
    tdead, cInv, rthInv, ambient, coolant, stopTime, auditPublishGuard, ...
    windowStart, windowStop, ...
    windowDuration, preflight, ...
    'VariableNames', {'Scenario_ID', 'Analysis_Tier', 'Parameter_Family', ...
    'Varied_Parameter', 'Source_Tag', 'Parameter_Semantics', 'HVPath_R_Ohm', ...
    'DCLink_C_F', 'Rs_Ohm', 'R_batt_heat_ref_Ohm', 'C_batt_J_K', ...
    'IGBT_Ron_Ohm', 'IGBT_Vf_V', 'IGBT_Eon_J', 'IGBT_Eoff_J', ...
    'PWM_tdead_s', 'C_inv_J_K', 'Rth_inv_K_W', 'Ambient_K', 'Coolant_K', ...
    'StopTime_s', 'Audit_Publish_Guard_s', 'Window_Start_s', 'Window_Stop_s', ...
    'Window_Duration_s', ...
    'Preflight'});
end

function nominal = nominalValues()
nominal = struct( ...
    'HVPath_R_Ohm', 0.01, ...
    'DCLink_C_F', 470e-6, ...
    'Rs_Ohm', 0.013, ...
    'R_batt_heat_Ohm', 0.4198, ...
    'C_batt_J_K', 26000, ...
    'IGBT_Ron_Ohm', 1e-3, ...
    'IGBT_Vf_V', 0.8, ...
    'IGBT_Eon_J', 22.86e-3, ...
    'IGBT_Eoff_J', 17.14e-3, ...
    'PWM_tdead_s', 1e-6, ...
    'C_inv_J_K', 3.06, ...
    'Rth_inv_K_W', 0.0966666666666667, ...
    'Ambient_K', 263.15, ...
    'Coolant_K', 263.15);
end

function in = applyScenario(in, modelName, paths, scenario)
in = in.setModelParameter('StopTime', scalarText(scenario.StopTime_s));
in = in.setBlockParameter(paths.HVPosR, 'R', scalarText(scenario.HVPath_R_Ohm));
in = in.setBlockParameter(paths.HVNegR, 'R', scalarText(scenario.HVPath_R_Ohm));
in = in.setBlockParameter(paths.DCLinkC, 'C', scalarText(scenario.DCLink_C_F));
in = in.setBlockParameter(paths.PMSM, 'Rs', scalarText(scenario.Rs_Ohm));
in = in.setBlockParameter(paths.RMSWindow, 'Value', scalarText(scenario.Window_Duration_s));
in = in.setBlockParameter(paths.HVLossGain, 'Gain', scalarText(2 * scenario.HVPath_R_Ohm));
in = in.setBlockParameter(paths.DCLinkEnergyGain, 'Gain', ...
    scalarText(0.5 * scenario.DCLink_C_F));
in = in.setBlockParameter(paths.DCLinkEnergyInitial, 'Value', '0');
in = in.setBlockParameter(paths.RsAudit, 'Value', scalarText(scenario.Rs_Ohm));
in = in.setBlockParameter(paths.RPackAudit, 'Value', ...
    scalarText(scenario.R_batt_heat_ref_Ohm));
in = in.setBlockParameter(paths.IGBTRon, 'Value', scalarText(scenario.IGBT_Ron_Ohm));
in = in.setBlockParameter(paths.IGBTVf, 'Value', scalarText(scenario.IGBT_Vf_V));
in = in.setBlockParameter(paths.Ambient, 'Value', scalarText(scenario.Ambient_K));
in = in.setBlockParameter(paths.Coolant, 'Value', scalarText(scenario.Coolant_K));

in = in.setBlockParameter(paths.IdPulse, 'Amplitude', '1');
in = in.setBlockParameter(paths.IdPulse, 'Period', '0.02');
in = in.setBlockParameter(paths.IdPulse, 'PulseWidth', '50');
in = in.setBlockParameter(paths.IdPulse, 'PhaseDelay', '0');
in = in.setBlockParameter(paths.IdScale, 'Gain', '80');
in = in.setBlockParameter(paths.IdOffset, 'Bias', '-40');
in = in.setBlockParameter(paths.IqRef, 'Value', '0');
in = in.setBlockParameter(paths.LimitId, 'Value', '40');
in = in.setBlockParameter(paths.LimitFrequency, 'Value', '50');
in = in.setBlockParameter(paths.LimitDuty, 'Value', '50');
in = in.setBlockParameter(paths.LimitPhase, 'Value', '0');
in = in.setBlockParameter(paths.LimitMode, 'Value', '4');
in = in.setBlockParameter(paths.LimitStatus, 'Value', '6');
in = in.setBlockParameter(paths.ClosedLoopEnable, 'Value', '1');

in = in.setVariable('M401C_T_ambient_K', scenario.Ambient_K, Workspace=modelName);
in = in.setVariable('M401C_Rth_hv_K_W', 10, Workspace=modelName);
in = in.setVariable('M401C_Rth_inv_K_W', scenario.Rth_inv_K_W, Workspace=modelName);
in = in.setVariable('M401C_C_hv_J_K', 200, Workspace=modelName);
in = in.setVariable('M401C_C_inv_J_K', scenario.C_inv_J_K, Workspace=modelName);
in = in.setVariable('M401C_C_batt_J_K', scenario.C_batt_J_K, Workspace=modelName);
in = in.setVariable('M401C_C_pmsm_stator_J_K', 100, Workspace=modelName);
in = in.setVariable('M401C_C_pmsm_rotor_J_K', 200, Workspace=modelName);
in = in.setVariable('M401C_IGBT_Iref_A', 600, Workspace=modelName);
in = in.setVariable('M401C_PWM_fsw_Hz', 2000, Workspace=modelName);
in = in.setVariable('M401C_IGBT_Eon_ref_J', scenario.IGBT_Eon_J, Workspace=modelName);
in = in.setVariable('M401C_IGBT_Eoff_ref_J', scenario.IGBT_Eoff_J, Workspace=modelName);
in = in.setVariable('M401C_IGBT_Vscale_ref', 0.228137066666667, Workspace=modelName);
in = in.setVariable('M401C_PWM_tdead_s', scenario.PWM_tdead_s, Workspace=modelName);
end

function record = collectRecord(out, scenario, enforceAssertions)
vBatt = getSignal(out, 'V_batt');
iBatt = getSignal(out, 'I_batt');
vDc = getSignal(out, 'V_dc_bus');
iDc = getSignal(out, 'I_dc');
pHv = getSignal(out, 'P_hv_loss');
kpi = getSignal(out, 'SystemKPI');
gates = getSignal(out, 'PWM_Gates');
idRef = getSignal(out, 'Id_Ref');
idFb = getSignal(out, 'Id_fb');
iqFb = getSignal(out, 'Iq_fb');
speed = getSignal(out, 'MechSpeed_rad_s');
reactionTorque = getSignal(out, 'MechReactionTorque_Nm');
closedLoop = getSignal(out, 'EnClosedLoop_Active');
eDc = getSignal(out, 'E_dc_link');
ledgerValid = getSignal(out, 'full_ledger_valid');

kpiData = signalData(kpi);
assert(size(kpiData, 2) >= 45, ...
    'SystemKPI does not expose the M4-01C ledger fields.');

startTime = scenario.Window_Start_s;
stopTime = scenario.Window_Stop_s;
duration = scenario.Window_Duration_s;
record = emptyRecord();
record.Scenario_ID = scenario.Scenario_ID;
record.Analysis_Tier = scenario.Analysis_Tier;
record.Parameter_Family = scenario.Parameter_Family;
record.Varied_Parameter = scenario.Varied_Parameter;
record.Source_Tag = scenario.Source_Tag;
record.Parameter_Semantics = scenario.Parameter_Semantics;
record.HVPath_R_Ohm = scenario.HVPath_R_Ohm;
record.DCLink_C_F = scenario.DCLink_C_F;
record.Rs_Ohm = scenario.Rs_Ohm;
record.R_batt_heat_ref_Ohm = scenario.R_batt_heat_ref_Ohm;
record.C_batt_J_K = scenario.C_batt_J_K;
record.IGBT_Ron_Ohm = scenario.IGBT_Ron_Ohm;
record.IGBT_Vf_V = scenario.IGBT_Vf_V;
record.IGBT_Eon_J = scenario.IGBT_Eon_J;
record.IGBT_Eoff_J = scenario.IGBT_Eoff_J;
record.PWM_tdead_s = scenario.PWM_tdead_s;
record.C_inv_J_K = scenario.C_inv_J_K;
record.Rth_inv_K_W = scenario.Rth_inv_K_W;
record.Ambient_K = scenario.Ambient_K;
record.Coolant_K = scenario.Coolant_K;
record.Audit_Publish_Guard_s = scenario.Audit_Publish_Guard_s;
record.Window_Start_s = startTime;
record.Window_Stop_s = stopTime;
record.Window_Duration_s = duration;
record.SimulationStop_s = out.tout(end);
record.ClosedLoop_Final = lastValue(closedLoop);
record.MaxAbsSpeed_rad_s = windowMaxAbs(speed, startTime, stopTime);
record.ReactionTorque_RMS_Nm = windowRms(reactionTorque, startTime, stopTime);
record.GateOverlap_Count = gateOverlapCount(gates, startTime, stopTime);
record.GateComplementMismatch_Count = gateMismatchCount(gates, startTime, stopTime);
record.IdRef_Min_A = windowMin(idRef, startTime, stopTime);
record.IdRef_Max_A = windowMax(idRef, startTime, stopTime);
record.IdFb_Mean_A = windowMean(idFb, startTime, stopTime);
record.IqFb_RMS_A = windowRms(iqFb, startTime, stopTime);
record.Vdc_Min_V = windowMin(vDc, startTime, stopTime);
record.Vdc_Max_V = windowMax(vDc, startTime, stopTime);
record.Vdc_Ripple_V = record.Vdc_Max_V - record.Vdc_Min_V;
record.Ibatt_RMS_A = windowRms(iBatt, startTime, stopTime);
record.Idc_RMS_A = windowRms(iDc, startTime, stopTime);
record.ModulationIndex_Mean = windowKpiMean(kpi, 7, startTime, stopTime);
record.ModulationIndex_Max = windowKpiMax(kpi, 7, startTime, stopTime);
record.VoltageMargin_Min_V = windowKpiMin(kpi, 8, startTime, stopTime);
record.ControlSaturation_Any = windowKpiAny(kpi, 17, startTime, stopTime);
record.T_batt_End_K = lastKpiValue(kpi, 13);
record.T_stator_End_K = lastKpiValue(kpi, 14);
record.T_rotor_End_K = lastKpiValue(kpi, 15);
record.P_batt_heat_Mean_W = windowKpiMean(kpi, 9, startTime, stopTime);
record.P_cu_Mean_W = windowKpiMean(kpi, 10, startTime, stopTime);
record.P_iron_Mean_W = windowKpiMean(kpi, 11, startTime, stopTime);
record.P_inv_Mean_W = windowKpiMean(kpi, 12, startTime, stopTime);
record.P_hv_loss_Model_W = lastKpiValue(kpi, 31);
record.P_batt_terminal_Model_W = lastKpiValue(kpi, 29);
record.P_dc_input_Model_W = lastKpiValue(kpi, 30);
record.P_dc_link_storage_Model_W = lastKpiValue(kpi, 32);
record.DeltaE_batt_Model_J = lastKpiValue(kpi, 35);
record.P_thermal_storage_Model_W = lastKpiValue(kpi, 39);
record.P_heat_rejection_Model_W = lastKpiValue(kpi, 40);
record.P_mech_Model_W = lastKpiValue(kpi, 38);
record.P_unmodeled_Model_W = lastKpiValue(kpi, 42);
record.Residual_dc_link_Model_W = lastKpiValue(kpi, 43);
record.EnergyLedgerValid_Final = lastValue(ledgerValid);
record.ElectricalLedgerValid_Final = lastKpiValue(kpi, 45);
record.KPI_Final_Time_s = kpi.Time(end);
record.RMS_Window_Elapsed_Model_s = lastKpiValue(kpi, 26);
record.RMS_Window_Complete_Model = lastKpiValue(kpi, 27);
record.RMS_Window_s_Model = lastKpiValue(kpi, 28);
record.P_batt_terminal_Recalc_W = windowProductMean(vBatt, iBatt, startTime, stopTime);
record.P_dc_input_Recalc_W = windowProductMean(vDc, iDc, startTime, stopTime);
record.P_hv_loss_Recalc_W = windowMean(pHv, startTime, stopTime);
record.DeltaE_batt_Recalc_J = -windowIntegralSum(vBatt, iBatt, kpi, 9, ...
    startTime, stopTime);
record.P_dc_link_storage_Recalc_W = windowEnergyRate(eDc, startTime, stopTime);
record.P_heat_input_Recalc_W = record.P_batt_heat_Mean_W + ...
    record.P_hv_loss_Recalc_W + record.P_inv_Mean_W + record.P_cu_Mean_W + ...
    record.P_iron_Mean_W;
record.P_thermal_balance_Error_W = record.P_heat_input_Recalc_W - ...
    record.P_thermal_storage_Model_W - record.P_heat_rejection_Model_W;
record.P_unmodeled_Recalc_W = -record.DeltaE_batt_Model_J / duration - ...
    record.P_dc_link_storage_Model_W - record.P_thermal_storage_Model_W - ...
    record.P_heat_rejection_Model_W - record.P_mech_Model_W;
record.Residual_dc_link_Recalc_W = record.P_batt_terminal_Recalc_W - ...
    record.P_hv_loss_Recalc_W - record.P_dc_link_storage_Model_W - ...
    record.P_dc_input_Recalc_W;
record.P_batt_terminal_AbsError_W = abs(record.P_batt_terminal_Model_W - ...
    record.P_batt_terminal_Recalc_W);
record.P_dc_input_AbsError_W = abs(record.P_dc_input_Model_W - ...
    record.P_dc_input_Recalc_W);
record.P_hv_loss_AbsError_W = abs(record.P_hv_loss_Model_W - ...
    record.P_hv_loss_Recalc_W);
record.DeltaE_batt_AbsError_J = abs(record.DeltaE_batt_Model_J - ...
    record.DeltaE_batt_Recalc_J);
record.P_dc_link_storage_AbsError_W = abs(record.P_dc_link_storage_Model_W - ...
    record.P_dc_link_storage_Recalc_W);
record.P_unmodeled_AbsError_W = abs(record.P_unmodeled_Model_W - ...
    record.P_unmodeled_Recalc_W);
record.Residual_dc_link_AbsError_W = abs(record.Residual_dc_link_Model_W - ...
    record.Residual_dc_link_Recalc_W);
record.HVLoss_Coeff_Ohm = record.P_hv_loss_Recalc_W / ...
    windowSquaredMean(iBatt, startTime, stopTime);
record.BattHeat_Coeff_Ohm = record.P_batt_heat_Mean_W / ...
    windowSquaredMean(iBatt, startTime, stopTime);
record.CuLoss_Coeff_Ohm = record.P_cu_Mean_W / ...
    (1.5 * windowSumSquaresMean(idFb, iqFb, startTime, stopTime));
record.Edc_Formula_AbsError_J = abs(lastValue(eDc) - ...
    0.5 * scenario.DCLink_C_F * lastValue(vDc)^2);
record.DeviceProtection_Evaluable = 0;
record.DeviceProtection_Status = "NOT_EVALUABLE";

validateOperationalRecord(record, scenario);
if enforceAssertions
    validateLedgerRecord(record);
end
end

function validateOperationalRecord(record, scenario)
assert(abs(record.SimulationStop_s - scenario.StopTime_s) < 1e-9, ...
    'Scenario %s did not reach the requested stop time.', record.Scenario_ID);
assert(record.GateOverlap_Count == 0, ...
    'Scenario %s detected gate overlap.', record.Scenario_ID);
assert(record.GateComplementMismatch_Count == 0, ...
    'Scenario %s detected gate complement mismatch.', record.Scenario_ID);
assert(record.ClosedLoop_Final == 1, ...
    'Scenario %s did not retain closed-loop mode.', record.Scenario_ID);
assert(record.MaxAbsSpeed_rad_s < 1e-9, ...
    'Scenario %s violated the zero-speed boundary.', record.Scenario_ID);
end

function validateLedgerRecord(record)
assert(record.EnergyLedgerValid_Final == 1, ...
    'Scenario %s did not retain a complete energy ledger.', record.Scenario_ID);
assert(record.ElectricalLedgerValid_Final == 1, ...
    'Scenario %s did not retain an electrical ledger.', record.Scenario_ID);
assert(record.P_batt_terminal_AbsError_W < 1e-10, ...
    'Scenario %s: battery terminal power independent recomputation failed.', ...
    record.Scenario_ID);
assert(record.P_dc_input_AbsError_W < 1e-10, ...
    'Scenario %s: DC input power independent recomputation failed.', ...
    record.Scenario_ID);
assert(record.P_hv_loss_AbsError_W < 1e-10, ...
    'Scenario %s: HV loss independent recomputation failed.', record.Scenario_ID);
assert(record.DeltaE_batt_AbsError_J < 1e-10, ...
    'Scenario %s: battery energy independent recomputation failed.', ...
    record.Scenario_ID);
assert(record.P_dc_link_storage_AbsError_W < 1e-10, ...
    'Scenario %s: DC-link storage independent recomputation failed.', ...
    record.Scenario_ID);
assert(abs(record.P_thermal_balance_Error_W) < 1e-10, ...
    'Scenario %s: thermal source/storage/rejection balance failed.', ...
    record.Scenario_ID);
assert(record.P_unmodeled_AbsError_W < 1e-10, ...
    'Scenario %s: system unmodeled-power independent recomputation failed.', ...
    record.Scenario_ID);
assert(record.Residual_dc_link_AbsError_W < 1e-10, ...
    'Scenario %s: DC boundary residual independent recomputation failed.', ...
    record.Scenario_ID);
end

function verifyResults(results)
assert(all(results.EnergyLedgerValid_Final == 1), ...
    'At least one scenario did not retain a complete energy ledger.');
assert(all(results.ElectricalLedgerValid_Final == 1), ...
    'At least one scenario did not retain an electrical ledger.');
assert(all(results.DeviceProtection_Evaluable == 0), ...
    'Device protection status must remain explicitly not evaluable.');
end

function verifyPreflight(results)
base = results(results.Scenario_ID == "B00_Base", :);
hvHigh = results(results.Scenario_ID == "B02_HVPathR_High", :);
dcHigh = results(results.Scenario_ID == "B04_DCLinkC_High", :);
rsHigh = results(results.Scenario_ID == "B06_Rs_High", :);
battRHigh = results(results.Scenario_ID == "B08_BattHeatR_High", :);
battCHigh = results(results.Scenario_ID == "B10_BattThermalC_High", :);
invLossHigh = results(results.Scenario_ID == "B12_InvLoss_High", :);
invCHigh = results(results.Scenario_ID == "B14_InvThermalC_High", :);
invRthHigh = results(results.Scenario_ID == "B16_InvThermalR_High", :);

assert(abs(base.HVLoss_Coeff_Ohm - 0.02) < 1e-6, ...
    'Baseline HV path injection was not applied.');
assert(abs(hvHigh.HVLoss_Coeff_Ohm - 0.04) < 1e-6, ...
    'HV path high injection was not applied.');
assert(dcHigh.Edc_Formula_AbsError_J < 1e-10, ...
    'DC-link capacitance high injection was not applied.');
assert(abs(rsHigh.CuLoss_Coeff_Ohm - rsHigh.Rs_Ohm) < 1e-6, ...
    'PMSM Rs high injection was not applied.');
assert(abs(battRHigh.BattHeat_Coeff_Ohm - battRHigh.R_batt_heat_ref_Ohm) < 1e-6, ...
    'Battery heat-source injection was not applied.');
assert(abs(battCHigh.P_thermal_storage_Model_W - base.P_thermal_storage_Model_W) > 1e-6, ...
    'Battery thermal-storage injection did not affect the ledger.');
assert(invLossHigh.P_inv_Mean_W > base.P_inv_Mean_W + 1e-6, ...
    'Inverter loss-package injection did not affect the ledger.');
assert(abs(invCHigh.P_thermal_storage_Model_W - base.P_thermal_storage_Model_W) > 1e-6, ...
    'Inverter thermal-capacitance injection did not affect the ledger.');
assert(abs(invRthHigh.P_heat_rejection_Model_W - base.P_heat_rejection_Model_W) > 1e-6, ...
    'Inverter thermal-resistance injection did not affect the ledger.');
end

function signal = getSignal(out, name)
names = out.logsout.getElementNames;
assert(any(strcmp(names, name)), 'Required logged signal is missing: %s', name);
signal = out.logsout.get(name).Values;
end

function value = windowKpiMean(signal, column, startTime, stopTime)
[time, data] = windowData(signal, startTime, stopTime);
value = trapz(time, data(:, column)) / (stopTime - startTime);
end

function value = windowKpiMin(signal, column, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = min(data(:, column));
end

function value = windowKpiMax(signal, column, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = max(data(:, column));
end

function value = windowKpiAny(signal, column, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = double(any(data(:, column) > 0.5));
end

function value = windowMean(signal, startTime, stopTime)
[time, data] = windowData(signal, startTime, stopTime);
value = trapz(time, data) / (stopTime - startTime);
end

function value = windowRms(signal, startTime, stopTime)
value = sqrt(windowSquaredMean(signal, startTime, stopTime));
end

function value = windowSquaredMean(signal, startTime, stopTime)
[time, data] = windowData(signal, startTime, stopTime);
value = trapz(time, data.^2) / (stopTime - startTime);
end

function value = windowSumSquaresMean(firstSignal, secondSignal, startTime, stopTime)
[firstTime, firstData] = windowData(firstSignal, startTime, stopTime);
[secondTime, secondData] = windowData(secondSignal, startTime, stopTime);
time = unique([firstTime; secondTime]);
first = interp1(firstTime, firstData, time, 'linear', 'extrap');
second = interp1(secondTime, secondData, time, 'linear', 'extrap');
value = trapz(time, first.^2 + second.^2) / (stopTime - startTime);
end

function value = windowMin(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = min(data);
end

function value = windowMax(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = max(data);
end

function value = windowMaxAbs(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = max(abs(data));
end

function value = windowProductMean(firstSignal, secondSignal, startTime, stopTime)
[firstTime, firstData] = windowData(firstSignal, startTime, stopTime);
[secondTime, secondData] = windowData(secondSignal, startTime, stopTime);
time = unique([firstTime; secondTime]);
first = interp1(firstTime, firstData, time, 'linear', 'extrap');
second = interp1(secondTime, secondData, time, 'linear', 'extrap');
value = trapz(time, first .* second) / (stopTime - startTime);
end

function value = windowIntegralSum(firstSignal, secondSignal, kpiSignal, column, startTime, stopTime)
[firstTime, firstData] = windowData(firstSignal, startTime, stopTime);
[secondTime, secondData] = windowData(secondSignal, startTime, stopTime);
[kpiTime, kpiData] = windowData(kpiSignal, startTime, stopTime);
time = unique([firstTime; secondTime; kpiTime]);
first = interp1(firstTime, firstData, time, 'linear', 'extrap');
second = interp1(secondTime, secondData, time, 'linear', 'extrap');
loss = interp1(kpiTime, kpiData(:, column), time, 'linear', 'extrap');
value = trapz(time, first .* second + loss);
end

function value = windowEnergyRate(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
value = (data(end) - data(1)) / (stopTime - startTime);
end

function [time, data] = windowData(signal, startTime, stopTime)
rawTime = signal.Time(:);
rawData = signalData(signal);
[sortedTime, order] = sort(rawTime);
sortedData = rawData(order, :);
[uniqueTime, lastIndex] = unique(sortedTime, 'last');
uniqueData = sortedData(lastIndex, :);
inside = uniqueTime > startTime & uniqueTime < stopTime;
time = [startTime; uniqueTime(inside); stopTime];
data = interp1(uniqueTime, uniqueData, time, 'linear', 'extrap');
end

function data = signalData(signal)
data = double(signal.Data);
if isvector(data)
    data = data(:);
end
assert(size(data, 1) == numel(signal.Time), 'Unexpected logged signal orientation.');
end

function value = lastValue(signal)
data = signalData(signal);
value = data(end, 1);
end

function value = lastKpiValue(signal, column)
data = signalData(signal);
value = data(end, column);
end

function count = gateOverlapCount(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
gates = data > 0.5;
count = sum((gates(:, 1) & gates(:, 2)) | (gates(:, 3) & gates(:, 4)) | ...
    (gates(:, 5) & gates(:, 6)));
end

function count = gateMismatchCount(signal, startTime, stopTime)
[~, data] = windowData(signal, startTime, stopTime);
gates = data > 0.5;
count = sum((gates(:, 1) == gates(:, 2)) | (gates(:, 3) == gates(:, 4)) | ...
    (gates(:, 5) == gates(:, 6)));
end

function text = scalarText(value)
text = num2str(value, '%.15g');
end

function record = emptyRecord()
record = struct( ...
    'Scenario_ID', "", ...
    'Analysis_Tier', "", ...
    'Parameter_Family', "", ...
    'Varied_Parameter', "", ...
    'Source_Tag', "", ...
    'Parameter_Semantics', "", ...
    'HVPath_R_Ohm', NaN, ...
    'DCLink_C_F', NaN, ...
    'Rs_Ohm', NaN, ...
    'R_batt_heat_ref_Ohm', NaN, ...
    'C_batt_J_K', NaN, ...
    'IGBT_Ron_Ohm', NaN, ...
    'IGBT_Vf_V', NaN, ...
    'IGBT_Eon_J', NaN, ...
    'IGBT_Eoff_J', NaN, ...
    'PWM_tdead_s', NaN, ...
    'C_inv_J_K', NaN, ...
    'Rth_inv_K_W', NaN, ...
    'Ambient_K', NaN, ...
    'Coolant_K', NaN, ...
    'Audit_Publish_Guard_s', NaN, ...
    'Window_Start_s', NaN, ...
    'Window_Stop_s', NaN, ...
    'Window_Duration_s', NaN, ...
    'SimulationStop_s', NaN, ...
    'ClosedLoop_Final', NaN, ...
    'MaxAbsSpeed_rad_s', NaN, ...
    'ReactionTorque_RMS_Nm', NaN, ...
    'GateOverlap_Count', NaN, ...
    'GateComplementMismatch_Count', NaN, ...
    'IdRef_Min_A', NaN, ...
    'IdRef_Max_A', NaN, ...
    'IdFb_Mean_A', NaN, ...
    'IqFb_RMS_A', NaN, ...
    'Vdc_Min_V', NaN, ...
    'Vdc_Max_V', NaN, ...
    'Vdc_Ripple_V', NaN, ...
    'Ibatt_RMS_A', NaN, ...
    'Idc_RMS_A', NaN, ...
    'ModulationIndex_Mean', NaN, ...
    'ModulationIndex_Max', NaN, ...
    'VoltageMargin_Min_V', NaN, ...
    'ControlSaturation_Any', NaN, ...
    'T_batt_End_K', NaN, ...
    'T_stator_End_K', NaN, ...
    'T_rotor_End_K', NaN, ...
    'P_batt_heat_Mean_W', NaN, ...
    'P_cu_Mean_W', NaN, ...
    'P_iron_Mean_W', NaN, ...
    'P_inv_Mean_W', NaN, ...
    'P_hv_loss_Model_W', NaN, ...
    'P_batt_terminal_Model_W', NaN, ...
    'P_dc_input_Model_W', NaN, ...
    'P_dc_link_storage_Model_W', NaN, ...
    'DeltaE_batt_Model_J', NaN, ...
    'P_thermal_storage_Model_W', NaN, ...
    'P_heat_rejection_Model_W', NaN, ...
    'P_mech_Model_W', NaN, ...
    'P_unmodeled_Model_W', NaN, ...
    'Residual_dc_link_Model_W', NaN, ...
    'EnergyLedgerValid_Final', NaN, ...
    'ElectricalLedgerValid_Final', NaN, ...
    'KPI_Final_Time_s', NaN, ...
    'RMS_Window_Elapsed_Model_s', NaN, ...
    'RMS_Window_Complete_Model', NaN, ...
    'RMS_Window_s_Model', NaN, ...
    'P_batt_terminal_Recalc_W', NaN, ...
    'P_dc_input_Recalc_W', NaN, ...
    'P_hv_loss_Recalc_W', NaN, ...
    'DeltaE_batt_Recalc_J', NaN, ...
    'P_dc_link_storage_Recalc_W', NaN, ...
    'P_heat_input_Recalc_W', NaN, ...
    'P_thermal_balance_Error_W', NaN, ...
    'P_unmodeled_Recalc_W', NaN, ...
    'Residual_dc_link_Recalc_W', NaN, ...
    'P_batt_terminal_AbsError_W', NaN, ...
    'P_dc_input_AbsError_W', NaN, ...
    'P_hv_loss_AbsError_W', NaN, ...
    'DeltaE_batt_AbsError_J', NaN, ...
    'P_dc_link_storage_AbsError_W', NaN, ...
    'P_unmodeled_AbsError_W', NaN, ...
    'Residual_dc_link_AbsError_W', NaN, ...
    'HVLoss_Coeff_Ohm', NaN, ...
    'BattHeat_Coeff_Ohm', NaN, ...
    'CuLoss_Coeff_Ohm', NaN, ...
    'Edc_Formula_AbsError_J', NaN, ...
    'DeviceProtection_Evaluable', NaN, ...
    'DeviceProtection_Status', "");
end
